spring:
  data:
    mongodb:
      host: ${MONGOHOST}
      port: ${MONGOPORT}
      database: PersonManagementDatabase
      username: ${MONGOUSER}
      password: ${MONGOPASSWORD}


#spring:
#  data:
#    mongodb:
#      uri: ${MONGO_URL}